name: Lint
on: [push]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          version: 14
      - name: install
        run: yarn
      - name: Lint with ESLint
        run: yarn lint
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          version: 14
      - name: install
        run: yarn
      - name: Lint with markdownlint
        run: yarn markdownlint
