name: Lint
on: [push]
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          version: 14
      - name: install
        run: yarn
      - name: lint
        run: yarn lint
